### ISSUE TITLE
Throwing an error for null author 

### ISSUE THREAD

**Issue by ErisDS** [novaugust/top-gh-contribs#10]
The Ghost build is currently failing because of an error where the API is returning a null author:

https://travis-ci.org/TryGhost/Ghost/jobs/64436672

**Comment by jaswilli** [comment]
My initial reaction is that a commit without an author is bad data and throwing an exception is the desired behavior.  I'd be curious to see if it was just a hiccup from the GitHub API or if there is actually a commit out there that just has no author data attached to it.

**Comment by ErisDS** [comment]
@jaswilli I know what you're getting at, but throwing an exception would equally break all builds and releases, which is why I filtered the bad data out instead.
