### ISSUE TITLE
Broken API url

### ISSUE THREAD

**Issue by LordAro** [novaugust/top-gh-contribs#15]
https://github.com/novaugust/top-gh-contribs/blob/master/index.js#L21 generates a URL that looks like `https://api.github.com/repos/tryghost/ghost/commits&page=1&per_page=100`
This is invalid and github correctly returns an invalid result - URL should be `https://api.github.com/repos/tryghost/ghost/commits?page=1&per_page=100` with a '?'

**Comment by cobbspur** [comment]
Good spot, the (?) query is built on https://github.com/novaugust/top-gh-contribs/blob/master/index.js#L12 and assumes a `sinceDate` value is provided. Either we add the `?` in the falsey case on L12 or just not add `page=1&per_page=100`, which is not really needed but it does reduces the number of requests sent.
