### ISSUE TITLE
Top contribs isn't an accurate reflection any more

### ISSUE THREAD

**Issue by ErisDS** [novaugust/top-gh-contribs#9]
For the last couple of releases, we've had less than 20 people and I've been wondering why. There also seem to have been people missing.

After a bit of digging, it seems to be because the /contributors/ endpoint only pulls from a list of the top 100 all time contributors, so to get into our top 20 from the last 90 days you must also be an all time top contributor. That means you essentially have to have been an early committer or have more than 1 commit. As the project gets older, it's going to get harder and harder to get into the list.

I'm not sure that this is really what we want to show. We want to be rewarding current contributors.

Therefore I think this little module may need to be rewritten to use the list commits endpoint:

https://developer.github.com/v3/repos/commits/#list-commits-on-a-repository

Use between right now, and now-90 days as the commit list, loop through and count up the commits and pick the top 20.

As a nice to have (but kinda complicated), the secondary ordering parameter after no. commits should be date, oldest commit first. i.e. lets assume the last 2 or 3 people in the 20 all have a single commit, the oldest committers should be shown, with the newest getting cut off the end. People with newer commits are more likely to get included next time and this is more fair than using the alphabet :)

**Comment by jaswilli** [comment]
Sounds reasonable.  I'm assuming `/repos/commits` includes merge commits, so those will have to be filtered out somehow.

**Comment by ErisDS** [comment]
Correct, they will need filtering - they always start with 'Merg...' in the message though so hopefully that's straightforward :)
